version: '3.0'
services: 
    angular:
        hostname: localhost
        build: App
        ports: 
            - "4200:4200"
    express:
        build: server
        ports: 
            - "3000:3000"